<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../../src/Fatewake.GameEngine/Fatewake.GameEngine.csproj" /><ProjectReference Include="../../src/Fatewake.Infrastructure/Fatewake.Infrastructure.csproj" /></ItemGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" /><PackageReference Include="xunit.v3" Version="3.1.0" /><PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" /></ItemGroup></Project>
